// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgRB_0fh0VC5oylr9JOXmpj5LyiLIMnzU',
    appId: '1:744348591067:web:34946205ee786cb954fdfe',
    messagingSenderId: '744348591067',
    projectId: 'mynotes-flutter-prj',
    authDomain: 'mynotes-flutter-prj.firebaseapp.com',
    storageBucket: 'mynotes-flutter-prj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEkGWhzs3SO-GMGdtHnMY8vRNLIqUlpo',
    appId: '1:744348591067:android:7c7105af00d7411c54fdfe',
    messagingSenderId: '744348591067',
    projectId: 'mynotes-flutter-prj',
    storageBucket: 'mynotes-flutter-prj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHBfXkeME9r1_702H20-gaBa5NHIBXhjQ',
    appId: '1:744348591067:ios:e1bb2fbd9062e7d154fdfe',
    messagingSenderId: '744348591067',
    projectId: 'mynotes-flutter-prj',
    storageBucket: 'mynotes-flutter-prj.appspot.com',
    iosClientId: '744348591067-182okqd6eem8siuuob51aqaa18250o52.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp0',
  );
}
